version: "2"
services:
  php:
    image: yiisoftware/yii2-php:7.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./docker/frontend/apache2/sites-enabled:/etc/apache2/sites-enabled
    ports:
      - '8020:80'
    networks:
      - default

  phpbackend:
    image: yiisoftware/yii2-php:7.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./docker/backend/apache2/sites-enabled:/etc/apache2/sites-enabled
    ports:
      - '8022:80'
    networks:
      - default

volumes:
  persistent: